---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Slaye.
--- DateTime: 08/03/2021 22:37
---

RegisterNetEvent("inventory:usedItem")
AddEventHandler(
        "inventory:usedItem",
        function(itemName, slot, data)
            local _source = source

            if itemName == "fortunecookie" then
                local removeResult = exports.inventory:removePlayerItem(_source, itemName, 1, data, slot)
                if removeResult == "done" then
                    TriggerClientEvent("fortunecookie:open", _source)
                end
            end
        end
)