Config = {}
Config.maxDistance = 5
Config.BloodObject = "p_bloodsplat_s"
Config.PoliceJob = { "police" }
Config.AmbulanceJob = { "ambulance" }
Config.Clothes = { "Unused (head)", "Masks", "Unused (hair)", "Upper Body", "Lower Body", "Bags & Parachutes", "Shoes", "Scarfs & Chains", "Shirt & Accessory", "Body Armor & Accessory 2", "Badges & Logos", "Shirt Overlay & Jackets" }
Config.Weapons = {
    --Handguns
    [GetHashKey("weapon_pistol")] = 'single',
    [GetHashKey("weapon_pistol_mk2")] = 'single',
    [GetHashKey("weapon_combatpistol")] = 'single',
    [GetHashKey("weapon_appistol")] = 'single',
    [GetHashKey("weapon_pistol50")] = 'single',
    [GetHashKey("weapon_snspistol")] = 'single',
    [GetHashKey("weapon_snspistol_mk2")] = 'single',
    [GetHashKey("weapon_heavypistol")] = 'single',
    [GetHashKey("weapon_vintagepistol")] = 'single',
    [GetHashKey("weapon_marksmanpistol")] = 'single',
    [GetHashKey("weapon_revolver")] = 'single',
    [GetHashKey("weapon_revolver_mk2")] = 'single',
    [GetHashKey("weapon_doubleaction")] = 'single',
    [GetHashKey("weapon_ceramicpistol")] = 'single',
    [GetHashKey("weapon_navyrevolver")] = 'single',
    [GetHashKey("weapon_gadgetpistol")] = 'single',
    [GetHashKey("weapon_stungun")] = 'single',

    --Submachine Guns
    [GetHashKey("weapon_microsmg")] = 'single',
    [GetHashKey("weapon_smg")] = 'single',
    [GetHashKey("weapon_smg_mk2")] = 'single',
    [GetHashKey("weapon_assaultsmg")] = 'single',
    [GetHashKey("weapon_combatpdw")] = 'single',
    [GetHashKey("weapon_machinepistol")] = 'single',
    [GetHashKey("weapon_minismg")] = 'single',

    --Shotguns
    [GetHashKey("weapon_pumpshotgun")] = 'single',
    [GetHashKey("weapon_pumpshotgun_mk2")] = 'single',
    [GetHashKey("weapon_sawnoffshotgun")] = 'single',
    [GetHashKey("weapon_assaultshotgun")] = 'single',
    [GetHashKey("weapon_bullpupshotgun")] = 'single',
    [GetHashKey("weapon_musket")] = 'single',
    [GetHashKey("weapon_heavyshotgun")]= 'single',
    [GetHashKey("weapon_dbshotgun")] = 'single',
    [GetHashKey("weapon_autoshotgun")] = 'single',
    [GetHashKey("weapon_combatshotgun")] = 'single',

    --AssaultRifle
    [GetHashKey("weapon_assaultrifle")] = 'single', --[-1074790547] = 'single',
    [GetHashKey("weapon_assaultrifle_mk2")] = 'single',
    [GetHashKey("weapon_carbinerifle")] = 'single',
    [GetHashKey("weapon_carbinerifle_mk2")] = 'single',
    [GetHashKey("weapon_advancedrifle")] = 'single',
    [GetHashKey("weapon_specialcarbine")] = 'single',
    [GetHashKey("weapon_specialcarbine_mk2")] = 'single',
    [GetHashKey("weapon_bullpuprifle")] = 'single',
    [GetHashKey("weapon_bullpuprifle_mk2")] = 'single',
    [GetHashKey("weapon_compactrifle")] = 'single',
    [GetHashKey("weapon_militaryrifle")] = 'single',

    --Light Machine Guns
    [GetHashKey("weapon_mg")] = 'single',
    [GetHashKey("weapon_combatmg")] = 'single',
    [GetHashKey("weapon_combatmg_mk2")] = 'single',
    [GetHashKey("weapon_gusenberg")] = 'single',

    --reticle sniper
    [GetHashKey("weapon_sniperrifle")] = 'reticle',
    [GetHashKey("weapon_heavysniper")] = 'reticle',
    [GetHashKey("weapon_heavysniper_mk2")] = 'reticle',
    [GetHashKey("weapon_marksmanrifle")] = 'reticle',
    [GetHashKey("weapon_marksmanrifle_mk2")]= 'reticle'

}

Config.VehicleWeapons = {
    GetHashKey("VEHICLE_WEAPON_ROTORS"),
    GetHashKey("VEHICLE_WEAPON_TANK"),
    GetHashKey("VEHICLE_WEAPON_SEARCHLIGHT"),
    GetHashKey("VEHICLE_WEAPON_RADAR"),
    GetHashKey("VEHICLE_WEAPON_PLAYER_BULLET"),
    GetHashKey("VEHICLE_WEAPON_PLAYER_LAZER"),
    GetHashKey("VEHICLE_WEAPON_ENEMY_LASER"),
    GetHashKey("VEHICLE_WEAPON_PLAYER_BUZZARD"),
    GetHashKey("VEHICLE_WEAPON_PLAYER_HUNTER"),
    GetHashKey("VEHICLE_WEAPON_PLANE_ROCKET"),
    GetHashKey("VEHICLE_WEAPON_SPACE_ROCKET"),
    GetHashKey("VEHICLE_WEAPON_TURRET_INSURGENT"),
    GetHashKey("VEHICLE_WEAPON_PLAYER_SAVAGE"),
    GetHashKey("VEHICLE_WEAPON_TURRET_TECHNICAL"),
    GetHashKey("VEHICLE_WEAPON_NOSE_TURRET_VALKYRIE"),
    GetHashKey("VEHICLE_WEAPON_TURRET_VALKYRIE"),
    GetHashKey("VEHICLE_WEAPON_CANNON_BLAZER"),
    GetHashKey("VEHICLE_WEAPON_TURRET_BOXVILLE"),
    GetHashKey("VEHICLE_WEAPON_RUINER_BULLET"),
    GetHashKey("VEHICLE_WEAPON_RUINER_ROCKET"),
    GetHashKey("VEHICLE_WEAPON_HUNTER_MG"),
    GetHashKey("VEHICLE_WEAPON_HUNTER_MISSILE"),
    GetHashKey("VEHICLE_WEAPON_HUNTER_CANNON"),
    GetHashKey("VEHICLE_WEAPON_HUNTER_BARRAGE"),
    GetHashKey("VEHICLE_WEAPON_TULA_NOSEMG"),
    GetHashKey("VEHICLE_WEAPON_TULA_MG"),
    GetHashKey("VEHICLE_WEAPON_TULA_DUALMG"),
    GetHashKey("VEHICLE_WEAPON_TULA_MINIGUN"),
    GetHashKey("VEHICLE_WEAPON_SEABREEZE_MG"),
    GetHashKey("VEHICLE_WEAPON_MICROLIGHT_MG"),
    GetHashKey("VEHICLE_WEAPON_DOGFIGHTER_MG"),
    GetHashKey("VEHICLE_WEAPON_DOGFIGHTER_MISSILE"),
    GetHashKey("VEHICLE_WEAPON_MOGUL_NOSE"),
    GetHashKey("VEHICLE_WEAPON_MOGUL_DUALNOSE"),
    GetHashKey("VEHICLE_WEAPON_MOGUL_TURRET"),
    GetHashKey("VEHICLE_WEAPON_MOGUL_DUALTURRET"),
    GetHashKey("VEHICLE_WEAPON_ROGUE_MG"),
    GetHashKey("VEHICLE_WEAPON_ROGUE_CANNON"),
    GetHashKey("VEHICLE_WEAPON_ROGUE_MISSILE"),
    GetHashKey("VEHICLE_WEAPON_BOMBUSHKA_DUALMG"),
    GetHashKey("VEHICLE_WEAPON_BOMBUSHKA_CANNON"),
    GetHashKey("VEHICLE_WEAPON_HAVOK_MINIGUN"),
    GetHashKey("VEHICLE_WEAPON_VIGILANTE_MG"),
    GetHashKey("VEHICLE_WEAPON_VIGILANTE_MISSILE"),
    GetHashKey("VEHICLE_WEAPON_TURRET_LIMO"),
    GetHashKey("VEHICLE_WEAPON_DUNE_MG"),
    GetHashKey("VEHICLE_WEAPON_DUNE_GRENADELAUNCHER"),
    GetHashKey("VEHICLE_WEAPON_DUNE_MINIGUN"),
    GetHashKey("VEHICLE_WEAPON_TAMPA_MISSILE"),
    GetHashKey("VEHICLE_WEAPON_TAMPA_MORTAR"),
    GetHashKey("VEHICLE_WEAPON_TAMPA_FIXEDMINIGUN"),
    GetHashKey("VEHICLE_WEAPON_TAMPA_DUALMINIGUN"),
    GetHashKey("VEHICLE_WEAPON_HALFTRACK_DUALMG"),
    GetHashKey("VEHICLE_WEAPON_HALFTRACK_QUADMG"),
    GetHashKey("VEHICLE_WEAPON_APC_CANNON"),
    GetHashKey("VEHICLE_WEAPON_APC_MISSILE"),
    GetHashKey("VEHICLE_WEAPON_APC_MG"),
    GetHashKey("VEHICLE_WEAPON_ARDENT_MG"),
    GetHashKey("VEHICLE_WEAPON_TECHNICAL_MINIGUN"),
    GetHashKey("VEHICLE_WEAPON_INSURGENT_MINIGUN"),
    GetHashKey("VEHICLE_WEAPON_TRAILER_QUADMG"),
    GetHashKey("VEHICLE_WEAPON_TRAILER_MISSILE"),
    GetHashKey("VEHICLE_WEAPON_TRAILER_DUALAA"),
    GetHashKey("VEHICLE_WEAPON_NIGHTSHARK_MG"),
    GetHashKey("VEHICLE_WEAPON_OPPRESSOR_MG"),
    GetHashKey("VEHICLE_WEAPON_OPPRESSOR_MISSILE"),
    GetHashKey("VEHICLE_WEAPON_MOBILEOPS_CANNON"),
    GetHashKey("VEHICLE_WEAPON_AKULA_TURRET_SINGLE"),
    GetHashKey("VEHICLE_WEAPON_AKULA_MISSILE"),
    GetHashKey("VEHICLE_WEAPON_AKULA_TURRET_DUAL"),
    GetHashKey("VEHICLE_WEAPON_AKULA_MINIGUN"),
    GetHashKey("VEHICLE_WEAPON_AKULA_BARRAGE"),
    GetHashKey("VEHICLE_WEAPON_AVENGER_CANNON"),
    GetHashKey("VEHICLE_WEAPON_BARRAGE_TOP_MG"),
    GetHashKey("VEHICLE_WEAPON_BARRAGE_TOP_MINIGUN"),
    GetHashKey("VEHICLE_WEAPON_BARRAGE_REAR_MG"),
    GetHashKey("VEHICLE_WEAPON_BARRAGE_REAR_MINIGUN"),
    GetHashKey("VEHICLE_WEAPON_BARRAGE_REAR_GL"),
    GetHashKey("VEHICLE_WEAPON_CHERNO_MISSILE"),
    GetHashKey("VEHICLE_WEAPON_COMET_MG"),
    GetHashKey("VEHICLE_WEAPON_DELUXO_MG"),
    GetHashKey("VEHICLE_WEAPON_DELUXO_MISSILE"),
    GetHashKey("VEHICLE_WEAPON_KHANJALI_CANNON"),
    GetHashKey("VEHICLE_WEAPON_KHANJALI_CANNON_HEAVY"),
    GetHashKey("VEHICLE_WEAPON_KHANJALI_MG"),
    GetHashKey("VEHICLE_WEAPON_KHANJALI_GL"),
    GetHashKey("VEHICLE_WEAPON_REVOLTER_MG"),
    GetHashKey("VEHICLE_WEAPON_WATER_CANNON"),
    GetHashKey("VEHICLE_WEAPON_SAVESTRA_MG"),
    GetHashKey("VEHICLE_WEAPON_SUBCAR_MG"),
    GetHashKey("VEHICLE_WEAPON_SUBCAR_MISSILE"),
    GetHashKey("VEHICLE_WEAPON_SUBCAR_TORPEDO"),
    GetHashKey("VEHICLE_WEAPON_THRUSTER_MG"),
    GetHashKey("VEHICLE_WEAPON_THRUSTER_MISSILE"),
    GetHashKey("VEHICLE_WEAPON_VISERIS_MG"),
    GetHashKey("VEHICLE_WEAPON_VOLATOL_DUALMG")
}

Config.Tank = {
    [GetHashKey("weapon_petrolcan")] = true,
    [GetHashKey("weapon_fireextinguisher")] = true,
    [GetHashKey("weapon_molotov")] = true,
    [GetHashKey("weapon_flare")] = true,
    [GetHashKey("weapon_ball")] = true,
    [GetHashKey("weapon_snowball")] = true,
    [GetHashKey("weapon_smokegrenade")] = true
}

Config.Animations = {
    "Ballistic",
    "Default",
    "Fat",
    "Female",
    "FirstPerson",
    "FirstPersonAiming",
    "FirstPersonFranklin",
    "FirstPersonFranklinAiming",
    "FirstPersonFranklinRNG",
    "FirstPersonFranklinScope",
    "FirstPersonMPFemale",
    "FirstPersonMichael",
    "FirstPersonMichaelAiming",
    "FirstPersonMichaelRNG",
    "FirstPersonMichaelScope",
    "FirstPersonRNG",
    "FirstPersonScope",
    "FirstPersonTrevor",
    "FirstPersonTrevorAiming",
    "FirstPersonTrevorRNG",
    "FirstPersonTrevorScope",
    "Franklin",
    "Gang",
    "Gang1H",
    "GangFemale",
    "Hillbilly",
    "MP_F_Freemode",
    "Michael",
    "SuperFat",
    "Trevor"
}

Config.Shell = {
    [GetHashKey("AMMO_PISTOL")] = "w_pi_singleshot_shell",
    [GetHashKey("AMMO_SMG")] = "w_pi_singleshot_shell",
    [GetHashKey("AMMO_SHOTGUN")] = "w_pi_flaregun_shell",
    [GetHashKey("AMMO_RIFLE")] = "w_pi_singleshot_shell",
    [GetHashKey("AMMO_FLAREGUN")] = "w_pi_flaregun_shell"
}